### ISSUE TITLE
Сonnect jenkins with our github, setup initial CI process (run tests on commit)

### ISSUE THREAD

**Issue by MikhailShumenko** [architecture-playground/playground-service#4]
Pls read how to connect jenkins with our github

we have to run tests after each push to branch
https://github.com/orgs/architecture-playground/dashboard (edited) 
for all java-services here

https://www.google.com/search?rlz=1C5CHFA_enDE884DE884&biw=1440&bih=766&sxsrf=ALeKk00b_J1QVk1oxUxylSE2Qm6_5p5siQ%3A1584532294210&ei=RgtyXoWfDI-RkwXVvI3oCw&q=run+jenkins+tests+github&oq=run+jenkins+tests+github&gs_l=psy-ab.3..35i39l2j0i22i30.59209.59632..60209...0.2..0.104.202.1j1......0....1..gws-wiz.......0i71.k33vVMylvXQ&ved=0ahUKEwiF2p_k-qPoAhWPyKQKHVVeA704FBDh1QMICw&uact=5

something similar to my google search

Also you should figure out what is Jenkinsfile and Jenkins pipeline

and tell me about that

**Comment by BulgakovAnton** [comment]
Yesterday i learn 3 hour with Jenkins and 4 hour with docker and docker compose . I learn today 5 hour  because have some trouble in home . P.S can't find command to tracking time.

**Comment by MikhailShumenko** [comment]
@BulgakovAnton it's okay. Github doesn't provide a time tracking feature.

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today began to better understand docker. And docker compose files. Did not find the difference between volumes and Mount

**Comment by BulgakovAnton** [comment]
:clock1: 8h Today i write docker-compose file and read documentation.

**Comment by BulgakovAnton** [comment]
:clock1: 7h 30m 
Today i have deal with dockerfile.

**Comment by BulgakovAnton** [comment]
:clock1: 7h 
today continue learn dockerfile and basic authentication.

**Comment by BulgakovAnton** [comment]
:clock1: 8h 
I cant do this script. But i'm not gave up. I do it.

**Comment by BulgakovAnton** [comment]
:clock1: 8h 
Today I studied requests and response, and continue little bit write script.

**Comment by BulgakovAnton** [comment]
:clock1: 8h 
Today I studied dockerfile tomorrow I will write it. I have power outages. Today I’m going to rest.

**Comment by BulgakovAnton** [comment]
:clock1: 8h 
today finish  writing dockerfile

**Comment by BulgakovAnton** [comment]
:clock1: 4h 
I have dockerfile running on Jenkins or Python. but I will find out what is happening. 
P.S If you are not busy, can we call at 21.15?

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today added Python to the docker file. I disassemble the SSH keys.

**Comment by BulgakovAnton** [comment]
:clock1: 8h  
read about jenkinsfile and pipeline. Now my laptop discharged.

Моя ошибка. я не досмотрел за временем и у меня погас ноут и не отправилось время. 
Сейчас дали свет на 10 минут. Почему то света нет только в моем и соседнем доме.  Я этот статус писал в 18.38. 

Просто написал что бы быть честным перед собой.

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Learning Jenkins file Job and Pipeline

**Comment by BulgakovAnton** [comment]
:clock1: 8h 
just read about build and pipeline jenkins.

**Comment by BulgakovAnton** [comment]
:clock1: 7h 30m
Today I connected our Jenkins to SSH GitHub. Then he began to deal with Pipeline, who was supposed to do Gradle Clean. Gradle is not installed in our docker compos file, I write it in it. But he does not launch it inside the container. And updated gradle to 6.3 on my laptop

**Comment by BulgakovAnton** [comment]
:clock1: 7h
Today I figured out a dockerfile.
