### ISSUE TITLE
Initial implementation for IaaC (jenkinsci/configuration-as-code-plugin)

### ISSUE THREAD

**Issue by MikhailShumenko** [architecture-playground/playground-service#6]
Please read more here: https://github.com/jenkinsci/configuration-as-code-plugin

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Add dockerfile and jenkinsfile to other services in architecture-playground, and start read about iaac

**Comment by MikhailShumenko** [comment]
Moved to Jenkins repo: https://github.com/architecture-playground/jenkins-docker-compose/issues/3
